version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - apps-net
    restart: unless-stopped

  wordpress-app:
    image: wordpress:latest
    container_name: wordpress-app
    depends_on:
      - mysql-db
    environment:
      WORDPRESS_DB_HOST: mysql-db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      VIRTUAL_HOST: devops-portfolio.pp.ua
      VIRTUAL_PORT: 80
    volumes:
      - wp_data:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - apps-net
    restart: unless-stopped

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    environment:
      - DEFAULT_HOST=wordpress-app
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - apps-net
    restart: unless-stopped

  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: always
    # Вставляємо токен прямо сюди для тесту
    command: tunnel --no-autoupdate run --token eyJhIjoiMTI2M2IyZTIxNGFiNDRjOTdjYTgzZjg1ODZhZjkwODUiLCJ0IjoiMjFjMTdlNjUtNzMxMy00ZTg3LWIwZWEtMTUwMzkwZmM4ZDhlIiwicyI6IlkyTTBabUkxTmpZdFltSmlNeTAwWWpjeUxUa3hPRFF0TmpjMlpXVTNaVEl3TkdaayJ9
    networks:
      - apps-net

  loki:
    build:
      context: .
      dockerfile: ./config/loki/Dockerfile
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - monitor-net
      - apps-net
    restart: unless-stopped

  promtail:
    build:
      context: .
      dockerfile: ./promtail/Dockerfile
    container_name: promtail
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    networks:
      - monitor-net
      - apps-net
    restart: unless-stopped



volumes:
  db_data:
  wp_data:
  conf:
  vhost:
  html:
  certs:

networks:
  apps-net:
    external: true
  monitor-net:
    external: true