version: '3.8'

services:
  # 1. MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - apps-net
    restart: unless-stopped

  # 2. WordPress
  wordpress-app:
    image: wordpress:latest
    container_name: wordpress-app
    depends_on:
      - mysql-db
    environment:
      WORDPRESS_DB_HOST: mysql-db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      VIRTUAL_HOST: devops-portfolio.pp.ua
      VIRTUAL_PORT: 80
    volumes:
      - wp_data:/var/www/html
    networks:
      - apps-net
    restart: unless-stopped

  # 3. Nginx Reverse Proxy
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    environment:
      - DEFAULT_HOST=wordpress-app
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - apps-net
    restart: unless-stopped

  # 4. Cloudflare Tunnel (Твій новий безкоштовний прохід)
  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: always
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMTI2M2IyZTIxNGFiNDRjOTdjYTgzZjg1ODZhZjkwODUiLCJ0IjoiMjFjMTdlNjUtNzMxMy00ZTg3LWIwZWEtMTUwMzkwZmM4ZDhlIiwicyI6IlkyTTBabUkxTmpZdFltSmlNeTAwWWpjeUxUa3hPRFF0TmpjMlpXVTNaVEl3TkdaayJ9
    command: tunnel --no-autoupdate run
    networks:
      - apps-net

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      # Монтуємо папку, а не файл. Docker Compose сам розрахує шлях відносно файлу.
      - ./config/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - apps-net

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - ./config/loki:/etc/promtail
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    networks:
      - apps-net

volumes:
  db_data:
  wp_data:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  apps-net:
    external: true


